version: '3.1'

services:
  c4po-api:
    build: '../../security-c4po-api'
    image: security-c4po-api:latest
    container_name: c4po-api
    environment:
      - SPRING_PROFILES_ACTIVE=COMPOSE
    depends_on:
      - c4po-db
      - c4po-keycloak
    links:
      - c4po-db
      - c4po-keycloak
    deploy:
      resources:
        limits:
          memory: "1G"
    ports:
      - 8443:8443
