version: '3.1'

services:
  c4po-keycloak:
    container_name: c4po-keycloak
    image: jboss/keycloak:11.0.3
    volumes:
      - ../cfg/c4po_realm_export.json:/tmp/c4po_realm_export.json
    ports:
      - 8888:8080
    env_file:
      - ../cfg/keycloak.env
  c4po-keycloak-postgress:
    container_name: c4po-keycloak-postgres
    image: postgres:latest
    env_file:
      - ../cfg/keycloakdb.env
    ports:
      - 5433:5432
    volumes:
      - ../volumes/keycloak/data:/var/lib/postgres/data
